[package]
name = 'jlink-rtx-plugin'
version = '1.0.0'
authors = ['Tal Risin <risint96@gmail.com>']
edition = '2018'

[dependencies]
pkg-version = '1.0.0'
log = '0.4.8'
ifmt = '0.3.0'
memchr = "2.3.3"

[build-dependencies]
bindgen = '0.53.2'

[lib]
name = 'rtx_plugin'
crate-type = ['dylib']
