[package]
name = 'jlink-rtx-plugin'
version = '1.0.0'
authors = ['Tal Risin <risint96@gmail.com>']
edition = '2018'

[dependencies]
pkg-version = '1.0.0'

[build-dependencies]
bindgen = '0.53.2'

[lib]
name = 'rtx_plugin'
crate-type = ['dylib']
